// ========== СЕРИАЛЫ ==========
// Добавляйте сюда только сериалы (type: "series")

const SERIES_LIST = [
    // ---------- СТАРЫЕ СЕРИАЛЫ (оставляем) ----------
    {
        id: "walking-dead",
        title: "Ходячие мертвецы",
        year: "2010",
        type: "series",
        kp_id: "228165",
        imdb_id: "tt1520211",
        tmdb_id: "1402",
        poster: "images/walking-dead.jpg",
        rating: "8.1",
        duration: "11 сезонов",
        genre: "Ужасы, Драма",
        description: "Культовый постапокалиптический сериал о шерифе Рике Граймсе."
    },
    {
        id: "korol-i-shut",
        title: "Король и Шут",
        year: "2023",
        type: "series",
        kp_id: "5364390",
        imdb_id: "",
        tmdb_id: "1161760",
        poster: "images/korol-i-shut.jpg",
        rating: "8.0",
        duration: "8 серий",
        genre: "Биография, Драма",
        description: "Байопик о легендарной панк-рок группе."
    },
    {
        id: "dutton-ranch",
        title: "Ранчо Даттонов",
        year: "2026",
        type: "series",
        kp_id: "7275308",
        imdb_id: "tt34991493",
        tmdb_id: "",
        poster: "images/dutton-ranch.jpg",
        rating: "8.0",
        duration: "1 сезон",
        genre: "Драма, Вестерн",
        description: "Приквел к сериалу Йеллоустоун."
    },
    {
        id: "the-dangers",
        title: "Семейка Дэнжерс",
        year: "2025",
        type: "series",
        kp_id: "10453030",
        imdb_id: "",
        tmdb_id: "",
        poster: "images/dangers.jpg",
        rating: "7.2",
        duration: "1 сезон",
        genre: "Комедия",
        description: "Семейная комедия."
    },
    {
        id: "historys-deadliest",
        title: "Самое страшное с Вингом Рэймсом",
        year: "2026",
        type: "series",
        kp_id: "12352718",
        imdb_id: "tt39221250",
        tmdb_id: "",
        poster: "images/historys-deadliest.jpg",
        rating: "7.5",
        duration: "1 сезон",
        genre: "Документальный",
        description: "Документальный сериал."
    },
    {
        id: "olivka-i-rex",
        title: "Оливка, Игорёк и Рекс",
        year: "2026",
        type: "series",
        kp_id: "8939376",
        imdb_id: "tt41528151",
        tmdb_id: "",
        poster: "images/olivka.jpg",
        rating: "8.0",
        duration: "1 сезон",
        genre: "Мультфильм",
        description: "Российский мультсериал."
    },
    {
        id: "partizany-2026",
        title: "Партизаны",
        year: "2026",
        type: "series",
        kp_id: "9106297",
        imdb_id: "tt38517049",
        tmdb_id: "322242",
        poster: "images/partizany.jpg",
        rating: "8.0",
        duration: "1 сезон",
        genre: "Военный",
        description: "Российский сериал о партизанах."
    },
    {
        id: "uchastkoviy-sasha",
        title: "Участковый Саша",
        year: "2025",
        type: "series",
        kp_id: "9102015",
        imdb_id: "",
        tmdb_id: "",
        poster: "images/uchastkoviy.jpg",
        rating: "7.5",
        duration: "1 сезон",
        genre: "Детектив",
        description: "Российский детективный сериал."
    },
    {
        id: "regular-show-lost-tapes",
        title: "Обычный мультик: Утерянные пленки",
        year: "2026",
        type: "series",
        kp_id: "5905719",
        imdb_id: "tt32604054",
        tmdb_id: "1650340",
        poster: "images/regular-show.jpg",
        rating: "8.0",
        duration: "1 сезон",
        genre: "Мультфильм",
        description: "Продолжение культового мультсериала."
    },

    // ---------- НОВЫЕ СЕРИАЛЫ (из вашего списка) ----------
    {
        id: "offside-2025",
        title: "Офсайд",
        year: "2025",
        type: "series",
        kp_id: "11111482",
        imdb_id: "tt38887576",
        tmdb_id: "",
        poster: "images/offside.jpg",
        rating: "0",
        duration: "1 сезон",
        genre: "Спорт, Драма",
        description: "Сериал о футболе и закулисных интригах."
    },
    {
        id: "unconditional-2026",
        title: "Безоговорочно",
        year: "2026",
        type: "series",
        kp_id: "11436282",
        imdb_id: "tt35668813",
        tmdb_id: "314916",
        poster: "images/unconditional.jpg",
        rating: "0",
        duration: "1 сезон",
        genre: "Драма",
        description: "История о любви и преданности."
    },
    {
        id: "love-is-never-gone-2026",
        title: "Любовь никогда не проходит",
        year: "2026",
        type: "series",
        kp_id: "12153685",
        imdb_id: "tt38941543",
        tmdb_id: "",
        poster: "images/love-is-never-gone.jpg",
        rating: "0",
        duration: "1 сезон",
        genre: "Мелодрама",
        description: "Романтическая история о потерянной и обретенной любви."
    },
    {
        id: "fate-chooses-you-2026",
        title: "Пара, созданная на небесах",
        year: "2026",
        type: "series",
        kp_id: "0",
        imdb_id: "tt41926853",
        tmdb_id: "",
        poster: "images/fate-chooses-you.jpg",
        rating: "0",
        duration: "1 сезон",
        genre: "Мелодрама",
        description: "Судьба сводит двух людей вопреки всем обстоятельствам."
    },
    {
        id: "believe-me-2026",
        title: "Поверьте мне",
        year: "2026",
        type: "series",
        kp_id: "0",
        imdb_id: "tt36789130",
        tmdb_id: "301283",
        poster: "images/believe-me.jpg",
        rating: "0",
        duration: "1 сезон",
        genre: "Драма, Триллер",
        description: "Психологическая драма о доверии и предательстве."
    },
    {
        id: "tou-sheng-2025",
        title: "Хитрость",
        year: "2025",
        type: "series",
        kp_id: "9821178",
        imdb_id: "",
        tmdb_id: "",
        poster: "images/tou-sheng.jpg",
        rating: "0",
        duration: "1 сезон",
        genre: "Криминал, Драма",
        description: "Китайский сериал о хитроумных аферах."
    },
    {
        id: "mia-2026",
        title: "Пропавшая без вести",
        year: "2026",
        type: "series",
        kp_id: "11297614",
        imdb_id: "tt33253070",
        tmdb_id: "262388",
        poster: "images/mia.jpg",
        rating: "0",
        duration: "1 сезон",
        genre: "Детектив, Триллер",
        description: "Расследование исчезновения человека."
    },
    {
        id: "legends-2026",
        title: "Легенды",
        year: "2026",
        type: "series",
        kp_id: "12197051",
        imdb_id: "tt33265765",
        tmdb_id: "262280",
        poster: "images/legends.jpg",
        rating: "0",
        duration: "1 сезон",
        genre: "Фэнтези, Приключения",
        description: "Эпические сказания о героях и мифах."
    },
    {
        id: "bienvenue-a-kingston-falls-2026",
        title: "Добро пожаловать в Кингстон-Фолс",
        year: "2026",
        type: "series",
        kp_id: "12300691",
        imdb_id: "tt40933472",
        tmdb_id: "317739",
        poster: "images/kingston-falls.jpg",
        rating: "0",
        duration: "1 сезон",
        genre: "Драма, Комедия",
        description: "Жизнь маленького городка со своими тайнами."
    },
    {
        id: "wu-2025",
        title: "ВУ",
        year: "2025",
        type: "series",
        kp_id: "0",
        imdb_id: "tt34881054",
        tmdb_id: "",
        poster: "images/wu.jpg",
        rating: "0",
        duration: "1 сезон",
        genre: "Боевик, История",
        description: "Исторический боевик о воинах."
    },
    {
        id: "talking-tom-shorts-2014",
        title: "Говорящий Том: Минимульты",
        year: "2014",
        type: "series",
        kp_id: "4420305",
        imdb_id: "tt13011686",
        tmdb_id: "219909",
        poster: "images/talking-tom.jpg",
        rating: "0",
        duration: "несколько сезонов",
        genre: "Мультфильм, Комедия",
        description: "Короткометражные мультфильмы с Говорящим Томом."
    },
    {
        id: "good-boys-go-to-heaven-2026",
        title: "Хорошие мальчики попадают в рай",
        year: "2026",
        type: "series",
        kp_id: "0",
        imdb_id: "tt38984263",
        tmdb_id: "",
        poster: "images/good-boys.jpg",
        rating: "0",
        duration: "1 сезон",
        genre: "Драма, Комедия",
        description: "История о подростках и их выборе."
    },
    {
        id: "meotjin-sinsegye-2026",
        title: "Дивный новый мир",
        year: "2026",
        type: "series",
        kp_id: "9420479",
        imdb_id: "tt38828946",
        tmdb_id: "303143",
        poster: "images/brave-new-world.jpg",
        rating: "0",
        duration: "1 сезон",
        genre: "Фантастика, Драма",
        description: "Антиутопический сериал по мотивам романа Хаксли."
    },
    {
        id: "zloi-gorod-2025",
        title: "Злой город",
        year: "2025",
        type: "series",
        kp_id: "1237984",
        imdb_id: "tt23033282",
        tmdb_id: "584855",
        poster: "images/zloi-gorod.jpg",
        rating: "0",
        duration: "1 сезон",
        genre: "Исторический, Боевик",
        description: "Российский исторический сериал о защитниках города."
    },
    {
        id: "la-casa-de-los-espiritus-2026",
        title: "Дом духов",
        year: "2026",
        type: "series",
        kp_id: "11884129",
        imdb_id: "tt33022938",
        tmdb_id: "259702",
        poster: "images/la-casa-espiritus.jpg",
        rating: "0",
        duration: "1 сезон",
        genre: "Драма, Мистика",
        description: "Экранизация романа Исабель Альенде."
    },
    {
        id: "buonvino-2026",
        title: "Буонвино — Тайны Вилла Боргезе",
        year: "2026",
        type: "series",
        kp_id: "0",
        imdb_id: "tt42053429",
        tmdb_id: "",
        poster: "images/buonvino.jpg",
        rating: "0",
        duration: "1 сезон",
        genre: "Детектив",
        description: "Итальянский детективный сериал."
    },
    {
        id: "kukushonok-2026",
        title: "Кукушонок",
        year: "2026",
        type: "series",
        kp_id: "5941145",
        imdb_id: "tt32827727",
        tmdb_id: "",
        poster: "images/kukushonok.jpg",
        rating: "0",
        duration: "1 сезон",
        genre: "Драма",
        description: "Российский сериал о сложных семейных отношениях."
    },
    {
        id: "kuzya-put-k-uspehu-2026",
        title: "Кузя. Путь к успеху",
        year: "2026",
        type: "series",
        kp_id: "8690650",
        imdb_id: "tt37846600",
        tmdb_id: "321438",
        poster: "images/kuzya.jpg",
        rating: "0",
        duration: "1 сезон",
        genre: "Комедия",
        description: "Приключения Кузи на пути к мечте."
    },
    {
        id: "kormilitsa-2026",
        title: "Кормилица",
        year: "2026",
        type: "series",
        kp_id: "12100471",
        imdb_id: "",
        tmdb_id: "",
        poster: "images/kormilitsa.jpg",
        rating: "0",
        duration: "1 сезон",
        genre: "Драма, История",
        description: "Российская историческая драма."
    },
    {
        id: "paris-police-1910-2026",
        title: "Парижская полиция 1910",
        year: "2026",
        type: "series",
        kp_id: "0",
        imdb_id: "tt42337009",
        tmdb_id: "257166",
        poster: "images/paris-police.jpg",
        rating: "0",
        duration: "1 сезон",
        genre: "Детектив, История",
        description: "Французский детектив начала XX века."
    },
    {
        id: "epoch-of-miyu-2026",
        title: "История Миюй",
        year: "2026",
        type: "series",
        kp_id: "0",
        imdb_id: "tt35288198",
        tmdb_id: "281231",
        poster: "images/miyu.jpg",
        rating: "0",
        duration: "1 сезон",
        genre: "Исторический, Драма",
        description: "Китайская историческая сага."
    },
    {
        id: "vanished-name-2026",
        title: "Исчезнувшее имя",
        year: "2026",
        type: "series",
        kp_id: "0",
        imdb_id: "tt31540954",
        tmdb_id: "270857",
        poster: "images/vanished-name.jpg",
        rating: "0",
        duration: "1 сезон",
        genre: "Триллер, Детектив",
        description: "Загадочное исчезновение человека."
    },
    {
        id: "jazz-ken-burns-2001",
        title: "Джаз",
        year: "2001",
        type: "series",
        kp_id: "280149",
        imdb_id: "tt0221300",
        tmdb_id: "20861",
        poster: "images/jazz.jpg",
        rating: "0",
        duration: "10 серий",
        genre: "Документальный, Музыка",
        description: "Документальный сериал Кена Бёрнса об истории джаза."
    },
    {
        id: "bing-hu-chong-sheng-2026",
        title: "Возрождение из ледяного озера",
        year: "2026",
        type: "series",
        kp_id: "12025842",
        imdb_id: "tt34903771",
        tmdb_id: "278894",
        poster: "images/bing-hu.jpg",
        rating: "0",
        duration: "1 сезон",
        genre: "Фэнтези, Приключения",
        description: "Китайское фэнтези о магии и возрождении."
    },
    {
        id: "detektiv-na-vse-ruki-2025",
        title: "Детектив на все руки. Дело о потерянном счастье",
        year: "2025",
        type: "series",
        kp_id: "8430996",
        imdb_id: "",
        tmdb_id: "",
        poster: "images/detektiv-na-vse-ruki.jpg",
        rating: "0",
        duration: "1 сезон",
        genre: "Детектив",
        description: "Российский детективный сериал."
    }
];